import type { Metadata } from 'next';
import '../styles/globals.css';

import { Toaster } from 'sonner';

import { geistMono, geistSans } from '@/styles/fonts';

export const metadata: Metadata = {
    title: 'Healthcare System',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
                <Toaster
                    position='top-center'
                    richColors
                />
            </body>
        </html>
    );
}
