import type { Metadata } from 'next';
import { Suspense } from 'react';
import '../styles/globals.css';

import { Toaster } from 'sonner';

import { SessionProvider } from '@/components/providers';
import { geistMono, geistSans } from '@/styles/fonts';

export const metadata: Metadata = {
    title: 'Healthcare System',
    description: 'Generated by create next app'
};

/**
 * Server component to fetch session without blocking the root layout.
 * Wrapped in Suspense to prevent blocking the entire page render.
 * 
 * This component is separated to avoid the Next.js 16 warning about
 * accessing headers() in the root layout.
 */
async function SessionFetcher({ children }: { children: React.ReactNode }) {
    try {
        // Dynamically import to avoid blocking root layout
        const { getSession } = await import('@/lib/auth/server');
        const session = await getSession();
        return <SessionProvider initialSession={session}>{children}</SessionProvider>;
    } catch (error) {
        // Fallback to null session if fetch fails
        console.error('Failed to fetch session in layout:', error);
        return <SessionProvider initialSession={null}>{children}</SessionProvider>;
    }
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Suspense
                    fallback={
                        <SessionProvider initialSession={null}>{children}</SessionProvider>
                    }
                >
                    <SessionFetcher>{children}</SessionFetcher>
                </Suspense>

                <Toaster
                    position='top-center'
                    richColors
                />
            </body>
        </html>
    );
}
